### ISSUE TITLE
Lbs 279 8vo

### ISSUE THREAD

**Issue by OrnElding** [Handrit/Manuscripts#1]
Það er villa í skráarheiti á handritinu Lbs 279 8vo. 
Skráarheitið er "Lbs08-0279" - það vantar "-is" endingu.
Spurt er: Hvernig laga ég það.

**Comment by kris-sigur** [comment]
Ég er búinn að laga þetta tiltekna handrit.

Þetta er einfaldlega lagað með því að breyta skráarnafninu. Í "Project" glugganum á Oxygen er hægt að hægri smella á skrána og velja "Rename". Síðan þarf að passa að msDesc xml:id stemmi eftir nafnabreytinguna.

Síðan þarf bara að stage/commit/push breytingar. Athugið að það koma tvær færslur í Git gluggan við þetta, ein fyrir skránna sem er verið að "eyða" og önnur fyrir "nýju" skránna.
